import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { CartSheet } from "@/components/cart/CartSheet";
import { WhatsAppButton } from "@/components/ui/WhatsAppButton";
import { SeasonalEffects } from "@/components/ui/SeasonalEffects";
import { getSettings } from "@/lib/db";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let settings = null;
  try {
    settings = await getSettings("store");
  } catch (error) {
    console.warn("Failed to fetch store settings during build/render:", error);
  }
  const gaId = settings?.googleAnalyticsId;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {gaId && <Script src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`} strategy="afterInteractive" />}
        {gaId && <Script id="google-analytics" strategy="afterInteractive">{`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${gaId}');`}</Script>}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        <Providers>
          <Navbar />
          <CartSheet />
          <div className="flex-1">
            {children}
          </div>
          <Footer />
          <WhatsAppButton />
          <SeasonalEffects />
        </Providers>
      </body>
    </html>
  );
}
